# Generated by Django 5.2.6 on 2025-10-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='volunteer_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
