# Generated by Django 5.2.6 on 2025-10-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_organization_join_code_alter_volunteer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='join_code',
            field=models.CharField(default='3694185DE8', max_length=10, unique=True),
        ),
    ]
