# Generated by Django 5.2.6 on 2025-10-19 11:18

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_organization_address_alter_organization_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='join_code',
            field=models.CharField(default=api.models.generate_join_code, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
